name: HandHeadAvatar
channels:
  - pytorch3d
  - pytorch
  - bottler
  - iopath
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py39h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.8.30=hbcca054_0
  - certifi=2024.7.4=py39h06a4308_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=12.4.127=h122497a_1
  - cuda-libraries=11.6.1=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.4.127=h06a4308_1
  - cuda-nsight-compute=12.4.1=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=12.4.127=h6a678d5_1
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=12.4.127=h6a678d5_1
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=12.4.127=h6a678d5_1
  - cuda-runtime=11.6.1=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.4.127=h99ab3db_1
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-version=12.4=hbda6634_3
  - cuda-visual-tools=11.6.1=0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.6.2=h6a678d5_0
  - ffmpeg=4.3.2=hca11adc_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - gds-tools=1.9.1.3=h99ab3db_1
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - iopath=0.1.9=py39
  - jpeg=9e=h5eee18b_1
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.9.2.110=h5e84587_0
  - libcublas-dev=11.9.2.110=h5c901ab_0
  - libcufft=10.7.1.112=hf425ae0_0
  - libcufft-dev=10.7.1.112=ha5ce4c0_0
  - libcufile=1.9.1.3=h99ab3db_1
  - libcufile-dev=1.9.1.3=h99ab3db_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurand-dev=10.3.5.147=h99ab3db_1
  - libcusolver=11.3.4.124=h33c3c4e_0
  - libcusparse=11.7.2.124=h7538f96_0
  - libcusparse-dev=11.7.2.124=hbbe9722_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.6.3.124=hd2722f0_0
  - libnpp-dev=11.6.3.124=h3c42840_0
  - libnvjpeg=11.6.2.124=hd473ad6_0
  - libnvjpeg-dev=11.6.2.124=hb5906b9_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hfdd30dd_2
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - nsight-compute=2024.1.1.4=h968f9c8_2
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - nvidiacub=1.10.0=0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h9ca470c_2
  - openssl=3.0.15=h5eee18b_0
  - pcre2=10.42=hebb0a14_1
  - portalocker=2.3.0=py39h06a4308_1
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.19=h955ad1f_1
  - python_abi=3.9=2_cp39
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.7.5=py39_cu116_pyt1130
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tabulate=0.9.0=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - typing_extensions=4.11.0=py39h06a4308_0
  - wheel=0.43.0=py39h06a4308_0
  - x264=1!161.3030=h7f98852_1
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - aadict==0.2.3
      - absl-py==2.1.0
      - accelerate==0.33.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - aitviewer==1.13.0
      - albucore==0.0.20
      - albumentations==1.4.21
      - aliyun-python-sdk-core==2.15.1
      - aliyun-python-sdk-kms==2.16.3
      - altair==5.3.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - appdirs==1.4.4
      - asset==0.6.13
      - asteval==1.0.6
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - bitarray==2.9.2
      - black==21.4b2
      - blinker==1.8.2
      - boto3==1.35.14
      - botocore==1.35.14
      - braceexpand==0.1.7
      - bvh-distance-queries==0.1.0
      - bvh-ray-tracing==0.1.0
      - camtools==0.1.7
      - cffi==1.16.0
      - chamferdist==1.0.3
      - chardet==5.2.0
      - chumpy==0.71
      - click==8.1.7
      - cloudpickle==3.0.0
      - coloredlogs==15.0.1
      - colorlog==6.8.2
      - comet-ml==3.40.0
      - comm==0.2.2
      - configargparse==1.7
      - configobj==5.0.8
      - configparser==7.1.0
      - contourpy==1.2.1
      - crcmod==1.7
      - cryptease==0.2.0
      - cryptography==42.0.8
      - cycler==0.12.1
      - cython==0.29.20
      - dash==2.17.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dataclasses-json==0.6.7
      - decorator==5.1.1
      - deprecated==1.2.14
      - detectron2==0.6
      - dill==0.3.9
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - dulwich==0.22.1
      - easydict==1.13
      - editdistance==0.8.1
      - einops==0.4.1
      - embreex==2.17.7.post6
      - entrypoints==0.4
      - eval-type-backport==0.2.0
      - everett==3.1.0
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - face-alignment==1.4.1
      - fairseq==0.9.0
      - fancycompleter==0.9.1
      - fastapi==0.100.1
      - fastjsonschema==2.20.0
      - fbxloader==0.0.2
      - ffmpy==0.3.3
      - filelock==3.14.0
      - flash-attn==2.6.3
      - flask==3.0.3
      - flatbuffers==24.3.25
      - fonttools==4.53.0
      - freetype-py==2.5.1
      - frozenlist==1.4.1
      - fsspec==2024.6.0
      - future==1.0.0
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glcontext==3.0.0
      - glfw==2.7.0
      - globre==0.1.5
      - gpytoolbox==0.3.1
      - gradio==3.39.0
      - gradio-client==1.1.1
      - grpcio==1.64.1
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.24.3
      - humanfriendly==10.0
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - ifaddr==0.2.0
      - imageio==2.34.1
      - imgui==2.0.0
      - importlib-metadata==7.2.1
      - importlib-resources==6.4.0
      - insightface==0.7.3
      - ipdb==0.13.13
      - ipycanvas==0.13.2
      - ipyevents==2.0.2
      - ipython==8.18.1
      - ipywidgets==8.1.3
      - itsdangerous==2.2.0
      - jax==0.4.30
      - jaxlib==0.4.30
      - jaxtyping==0.2.36
      - jedi==0.19.1
      - jinja2==3.1.4
      - jiter==0.8.2
      - jmespath==0.10.0
      - joblib==1.4.2
      - json-tricks==3.17.3
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==7.4.9
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.11
      - kaleido==0.2.1
      - kaolin==0.15.0
      - kiwisolver==1.4.5
      - knn-cuda==0.2
      - kornia==0.6.12
      - lightglue==0.0
      - lightning-utilities==0.11.2
      - linkify-it-py==2.0.3
      - llvmlite==0.43.0
      - lmfit==1.3.2
      - loguru==0.7.2
      - lpips==0.1.4
      - lxml==5.2.2
      - mako==1.3.9
      - mano==0.1
      - manopth==0.0.1
      - markdown==3.6
      - markdown-it-py==2.2.0
      - markdown2==2.4.10
      - markupsafe==2.1.5
      - marshmallow==3.21.3
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - mediapipe==0.10.15
      - ml-dtypes==0.5.0
      - mmcv==1.3.9
      - mmengine==0.10.4
      - model-index==0.1.11
      - moderngl==5.11.1
      - moderngl-window==2.4.6
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - multipledispatch==1.0.0
      - munkres==1.1.4
      - mypy-extensions==1.0.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - nltk==3.9.1
      - numba==0.60.0
      - numpy==1.23.5
      - nvdiffrast==0.3.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - onnx==1.17.0
      - onnxruntime==1.19.2
      - open3d==0.18.0
      - opencv-contrib-python==4.10.0.84
      - opencv-contrib-python-headless==4.10.0.84
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.1
      - opt-einsum==3.4.0
      - ordered-set==4.1.0
      - orjson==3.10.6
      - oss2==2.17.0
      - packaging==24.1
      - pandas==2.2.2
      - parso==0.8.4
      - pathspec==0.12.1
      - pathtools==0.1.2
      - pdbpp==0.10.3
      - peft==0.4.0
      - pexpect==4.9.0
      - pillow==9.5.0
      - pip==24.3.1
      - platformdirs==4.2.2
      - plotly==5.22.0
      - plyfile==1.1
      - prettytable==3.10.2
      - promise==2.3
      - prompt-toolkit==3.0.47
      - protobuf==3.20.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyassimp==5.2.5
      - pybind11==2.12.0
      - pycocotools==2.0.6
      - pycolmap==0.4.0
      - pycparser==2.22
      - pycryptodome==3.20.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydeprecate==0.3.1
      - pydot==3.0.1
      - pydub==0.25.1
      - pyfbx==0.0.8
      - pygit2==1.10.1
      - pyglet==2.0.17
      - pygments==2.18.0
      - pyhocon==0.3.59
      - pymcubes==0.1.6
      - pymeshio==3.0.1
      - pymeshlab==2022.2.post4
      - pyopengl==3.1.0
      - pyparsing==2.4.7
      - pyqt5==5.12.3
      - pyqt5-qt5==5.15.15
      - pyqt5-sip==12.15.0
      - pyquaternion==0.9.9
      - pyrender==0.1.45
      - pyrepl==0.9.0
      - pyrootutils==1.0.4
      - pyrr==0.10.3
      - pysdf==0.1.9
      - python-box==6.1.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytools==2024.1.14
      - pytorch-lightning==1.5.7
      - pytz==2023.4
      - pywavelets==1.6.0
      - pyyaml==5.4.1
      - pyzmq==24.0.1
      - quaternion==3.5.2.post4
      - ray==2.6.1
      - referencing==0.35.1
      - regex==2024.7.24
      - requests==2.28.2
      - requests-toolbelt==1.0.0
      - rerun==1.0.30
      - retrying==1.3.4
      - rich==13.4.2
      - robust-loss-pytorch==0.0.2
      - roma==1.5.0
      - rpds-py==0.18.1
      - s3transfer==0.10.2
      - sacrebleu==2.4.3
      - safetensors==0.4.3
      - scikit-image==0.18.1
      - scikit-learn==1.5.0
      - scikit-video==1.1.11
      - scipy==1.13.1
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.6.0
      - setproctitle==1.3.3
      - setuptools==60.2.0
      - shortuuid==1.0.11
      - simpleicp==2.0.15
      - simplejson==3.19.2
      - simsimd==6.0.1
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sounddevice==0.5.1
      - soupsieve==2.5
      - spatial-correlation-sampler==0.5.0
      - stack-data==0.6.3
      - starlette==0.27.0
      - stringzilla==3.10.7
      - submitit==1.5.1
      - subprocess32==3.5.4
      - supervision==0.6.0
      - sympy==1.13.3
      - tenacity==8.4.1
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.3.0
      - threadpoolctl==3.5.0
      - tifffile==2024.6.18
      - timm==1.0.9
      - tinycudann==1.7
      - tokenizers==0.13.3
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.1
      - torch==1.13.0+cu117
      - torch-dct==0.1.6
      - torch-ema==0.3
      - torchaudio==0.13.0+cu117
      - torchfile==0.1.0
      - torchgeometry==0.1.2
      - torchmetrics==1.4.0.post0
      - torchvision==0.14.0+cu117
      - tornado==6.4.1
      - tqdm==4.65.2
      - traitlets==5.14.3
      - transformers==4.31.0
      - trimesh==3.23.5
      - triton==3.0.0
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - uc-micro-py==1.0.3
      - uncertainties==3.2.2
      - unknown==0.0.0
      - urllib3==1.26.19
      - usd-core==23.5
      - uvicorn==0.23.2
      - wandb==0.12.9
      - wcwidth==0.2.13
      - webdataset==0.2.100
      - websocket-client==1.3.3
      - websockets==11.0.3
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.11
      - wmctrl==0.5
      - wrapt==1.16.0
      - wurlitzer==3.1.1
      - xatlas==0.0.9
      - xtcocotools==1.14.3
      - yacs==0.1.8
      - yapf==0.40.2
      - yarl==1.9.4
      - yaspin==3.0.2
      - zeroconf==0.140.1
      - zipp==3.19.2
